# Generated by Django 2.1.1 on 2018-09-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=15)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shoes')),
            ],
        ),
        migrations.AlterField(
            model_name='shoes_size',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shoes'),
        ),
    ]
