# Generated by Django 2.1.1 on 2018-09-14 16:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shoes_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='size',
            new_name='sizes',
        ),
        migrations.AddField(
            model_name='shoes',
            name='images',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='images_3d',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
