# Generated by Django 2.1.1 on 2018-09-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180926_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_cart',
            name='slug',
        ),
    ]
